apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskapp-uploads-pvc
  namespace: production
  labels:
    app: taskapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
